spring.application.name=gov-erp

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/gov_erp_db
spring.datasource.username=postgres
spring.datasource.password=edouard
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.writer-with-default-pretty-printer=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=list

# Error handling
server.error.include-message=always
server.error.include-stacktrace=on-param
